hostname_additional_hosts:
  - ip_address: 85.215.157.19
    hostname: de-1010-xl.imsawadogo.com
    hostname_short: "de-1010-xl"
  # - ip_address: 5.6.7.8
  #   hostname: b.example.com
  #   hostname_short: b
#
apt_hst_strt_srvc_lst: # Ensure Services are running.
  - chronyd
  - bind9
  - psa
#
#  ## PRVS | CONFIG  ###
prvs_copy_home: true # Copy default user's home files in place
prvs_root_passwd: true # update root passward
#
dkr_copy_def_files: false # Copy default docker files to target server
dkr_copy_etx_files: false #  # Copy extended docker files to target host

crntb_activate_cronjobs: false
#
ansible_become_pass: "{{ localhost_become_pass }}"
#
#
#  ## APT | PACKAGES INSTALL  ###
instl_def_pckg: true # Install complete packages. A 'no' will remove it from the host (apt_def_pckg_lst)
instl_utl_pckg: true # Install complete packages. A 'no' will remove it from the host (apt_util_lst)
sysd_strt_srvc: true # Start services
instl_ansbl_pckg: false # Install ansible using PIP (pip_ansbl_pckg_lst apt_ansbl_pckg_lst)
instl_docker_pckg: true # Install Docker package (apt_docker_pckg_lst)
instl_gthb_ky: true # add id_rsa to only ibrahim to allow local server access to git
apt_host_pckg_lst: # Install Host Specific Packages (keep this empty. use host_var to overwrite it)
  - bind9
  - telnetd
  - telnet # systemctl status inetd
dckr_fldr_lst: # Docker folder list that will be copied when set in the host variable
  - { fldr: "4a999ff" }

crntb_fldr_lst: # Crontab folder list that will be copied when set in the host variable
  - { fldr: "4a999ff" }
#
# my ignore ip list for fail2ban is here: /etc/fail2ban/jail.local
fail2ban_whitelist: true # Enable Fail2Ban whitelist configuration
#
crntb_actvt_crnjbs_mrym: false
dckr_dpl_meryem: false
dckr_dpl_anasse: false
dckr_dpl_opendot: false
dckr_dpl_skyline: false
dckr_dpl_reddot_africa: true
dckr_dpl_blingbody: false
dckr_dpl_activ: false
dckr_dpl_jmj: false
#
ansible_python_interpreter: /usr/bin/python3
