hostname_additional_hosts:
  - ip_address: 192.168.77.213
    hostname: mdsrvr.skyline.lan
    hostname_short: mdsrvr

  #
# virthost01.skyline.lan:
ansible_connection: local  # this will overwrite any other type of connections. its needed here.
ansible_become_pass: "{{ localhost_become_pass }}"
#
#  ## PRVS | CONFIG  ###
prvs_copy_home: true  # Copy default user's home files in place
prvs_root_passwd: true  # update root passward
#
dkr_copy_def_files: no  # Copy default docker files to target server
#
crntb_activate_cronjobs: no
#
#
#  ## APT | PACKAGES INSTALL  ###
instl_def_pckg: true  # Install complete packages. A 'no' will remove it from the host (apt_def_pckg_lst)
instl_utl_pckg: true  # Install complete packages. A 'no' will remove it from the host (apt_util_lst)
sysd_strt_srvc: true  # Start services
instl_ansbl_pckg: no  # Install ansible using PIP (pip_ansbl_pckg_lst apt_ansbl_pckg_lst)
instl_docker_pckg: true  # Install Docker package (apt_docker_pckg_lst)
apt_host_pckg_lst:  # Install Host Specific Packages (keep this empty. use host_var to overwrite it)

pip_host_pckg_lst:  # Install Host Specific PIP Packages when ansible is also installed
