---
# ansible-galaxy collection install -r 
# ansible-galaxy collection install community.healthchecksio --upgrade
# roles:
#   - name: community.docker
#   #- src: https://github.com/

roles:
  - name: geerlingguy.docker
#
collections:
  - name: community.healthchecksio  # ansible-galaxy collection install community.healthchecksio