---
# defaults file for dockers
#
dkr_copy_def_files: yes # Copy default docker files to target host
#
dkr_copy_etx_files: no # Copy extended docker files to target host
#
dckr_fldr_lst: # Docker folder list that will be copied when set in the host variable
  - { fldr: "none" }
#
dsbl_dhcpvsx: no # Disable dhcp v6
#
dckr_dpl_emby_gh: no
#
# /*******/
# find a way to declare them in the same file where they are needed
working_dir: "{{dckr_bs_pth}}/meryem-8090/"
working_dir_skyline: "{{dckr_bs_pth}}/skyline-8094/"
log_dir: "{{ working_dir}}logs"
# /*******/
dckr_dmain_nme_pstfx: home.sawadogo.xyz
#
#
# docker containers
dckr_dpl_pihole: no
dckr_dpl_iSpy: no
dckr_dpl_semaphore: no
dckr_dpl_npxymgmt: no
dckr_dpl_trcmmnd: no
dckr_dpl_gravity: no
dckr_dpl_homepage: no
dckr_dpl_plex: no
dckr_dpl_plex_gh: no
dckr_dpl_tubesync: no
dckr_dpl_youtubedl: no
dckr_dpl_opnsbttls: no
dckr_dpl_tautulli: no
dckr_dpl_overseerr: no
dckr_dpl_emby: no
dckr_dpl_invdus: no
dckr_dpl_rxrsum: no
dckr_dpl_rsume: no
dckr_dpl_wud: no
dckr_dpl_webpdf: no
dckr_dpl_meryem: no
dckr_dpl_anasse: no
dckr_dpl_opendot: no
dckr_dpl_skyline: no
dckr_dpl_reddot_africa: no
dckr_dpl_blingbody: no
dckr_dpl_webcheck: no
dckr_dpl_uptmkm: no
dckr_dpl_activ: no
dckr_dpl_spotube: no
dckr_dpl_jmj: no
dckr_dpl_gpt: no
dckr_dpl_rustdesk: no
dckr_dpl_n8n: false

#
include_vars:
  file: n8n.yml
