npm_container_name: "nginx_proxy_manager"
npm_image_name: "jc21/nginx-proxy-manager"
npm_image_tag: "latest"
npm_image_full: "{{ npm_image_name }}:{{ npm_image_tag }}"
npm_workdir: "/opt/docker/nginx_proxy_manager-8081/"
npm_data_dir: "/opt/docker/nginx_proxy_manager-8081/data"
npm_letsencrypt_dir: "/opt/docker/nginx_proxy_manager-8081/letsencrypt"
npm_timezone: "Europe/Berlin"