ytdl_image_name: "tzahi12345/youtubedl-material"
ytdl_image_tag: "latest"
ytdl_image_full: "{{ ytdl_image_name }}:{{ ytdl_image_tag }}"
ytdl_service_name: "youtubedl"
ytdl_container_name: "YoutubeDl_con"
ytdl_hostname: "ytdl.skyline.lan"
ytdl_project_name: "YoutubeDl"
ytdl_timezone: "Europe/Berlin"
ytdl_http_user: "ibrahim"
ytdl_puid_env: "${UID}" # or "1000"
ytdl_pgid_env: "${GID}" # or "1000"
ytdl_base_dir: "/opt/docker/youtubedl-8084"
