---
# vars file for configs
webpages:
  - url: "https://example.com/login"
    username: "user1"
    password: "password1"
    logout_url: "https://example.com/logout"
  - url: "https://another-site.com/login"
    username: "user2"
    password: "password2"
    logout_url: "https://another-site.com/logout"
#
# gnomerdp
gnome_packages:
  - gnome-remote-desktop
#
# docker
docker_users:
  - "{{ ansible_user }}"

docker_daemon_config:
  log-driver: "json-file"
  log-opts:
    max-size: "10m"
    max-file: "3"
  storage-driver: "overlay2"
#
