---
# tasks file for dockers
- name: Job 01 | Copy default docker files to "inventory_hostname"
  copy:
    src: "files/docker"
    dest: "/opt/"
    owner: ibrahim
    group: ibrahim
    mode: "0744"
  when: ansible_os_family | default('Debian') == "Debian" and dkr_copy_def_files  # inventory_hostname != 'virthost01' or inventory_hostname != '4a999ff'

- name: Job 02 | Copy extended docker files to target host
  copy:
    src: "files/a35a0d3/docker"
    dest: "/opt/"
    owner: ibrahim
    group: ibrahim
    mode: "0744"
  when: ansible_os_family | default('Debian') == "Debian" and dkr_copy_etx_files  # inventory_hostname == 'a35a0d3'

- name: Job 03 | Copy Specific docker folder(s) to target host
  copy:
    src: "files/{{ inventory_hostname }}/docker"
    # src: "files/{{item.fldr}}/docker"
    dest: "/opt/"
    owner: ibrahim
    group: ibrahim
    mode: "0744"
  # with_items:
  # "{{ dckr_fldr_lst }}"
  # when: dckr_fldr_lst.0 is defined
  tags:
    -  #test
#
# TODO: find a way to imporve the copy - shut it down and use docker deploy
- name: Job 04 | Copy docker folder(s) to target host that matches {{ inventory_hostname }}"
  copy:
    src: "files/{{ inventory_hostname }}/docker"
    dest: "/opt/"
    owner: ibrahim
    group: ibrahim
    mode: "0744"
  # when: inventory_hostname != 'virthost01'
#
- name: Job 08 | import task watchtower
  ansible.builtin.import_tasks:
    file: 0000-watchtower.yml
  # when: apt_host_pckg_lst | contains bind9
#
- name: Job 09 | import task dozzle
  ansible.builtin.import_tasks:
    file: 8892-dozzle.yml
  # when: apt_host_pckg_lst | contains bind9
#
- name: Job 10 | import task iSpy
  ansible.builtin.import_tasks:
    file: 8099-iSpy.yml
  # when: apt_host_pckg_lst | contains bind9
#
- name: Job 11 | import task semaphore
  ansible.builtin.import_tasks:
    file: 3002-semaphore.yml
  when: instl_docker_pckg and dckr_dpl_semaphore
  tags:
    - semaphore
    # - test
#
- name: Job 12 | import task 8081 nginx proxy manager
  ansible.builtin.import_tasks:
    file: 8081-nginx_proxy_manager.yml
  when: instl_docker_pckg and dckr_dpl_npxymgmt
  tags:
    - nginx
    # - test
#
- name: Job 13 | import task truecommand
  ansible.builtin.import_tasks:
    file: 3006-truecommand.yml
  # when: apt_host_pckg_lst | contains bind9
#
- name: Job 14 | import task pihole
  ansible.builtin.import_tasks:
    file: 8080-pihole.yml
  when: instl_docker_pckg and dckr_dpl_pihole
  tags:
    - pihole
  # - test
#
- name: Job 15 | import task gravity
  ansible.builtin.import_tasks:
    file: 8008-gravity.yml
  # when: apt_host_pckg_lst | contains bind9
#
- name: Job 16 | import task homepage
  ansible.builtin.import_tasks:
    file: 3550-homepage.yml
  # when: apt_host_pckg_lst | contains bind9
#
- name: Job 17 | import task plex
  ansible.builtin.import_tasks:
    file: 32400-plex.yml
  when: instl_docker_pckg and dckr_dpl_plex
#
- name: Job 17.1 | import task plex
  ansible.builtin.import_tasks:
    file: 32400-plex-gh.yml
  when: instl_docker_pckg and dckr_dpl_plex_gh
  tags:
    - plex
  # - test
#
- name: Job 18 | import task tubesync
  ansible.builtin.import_tasks:
    file: 4848-tubesync.yml
  # when: apt_host_pckg_lst | contains bind9
#
- name: Job 19 | import task YoutubeDl
  ansible.builtin.import_tasks:
    file: 8084-youtubedl.yml
  when: instl_docker_pckg and dckr_dpl_youtubedl
  tags:
    - youtubedl
    # - test

#
- name: Job 20 | import task opensubtitles
  ansible.builtin.import_tasks:
    file: 0000-opensubtitles.yml
  # when: apt_host_pckg_lst | contains bind9
#
- name: Job 21 | import task tautulli
  ansible.builtin.import_tasks:
    file: 8181-tautulli.yml
  # when: apt_host_pckg_lst | contains bind9
#
- name: Job 22 | import task overseerr
  ansible.builtin.import_tasks:
    file: 5055-overseerr.yml
  when: instl_docker_pckg and dckr_dpl_overseerr
  tags:
    - overseerr
    # - test
#
- name: Job 23 | import task emby
  ansible.builtin.import_tasks:
    file: 8096-emby.yml
  # when: apt_host_pckg_lst | contains bind9
#
- name: Job 23.1 | import task emby
  ansible.builtin.import_tasks:
    file: 8096-emby-gh.yml
  when: instl_docker_pckg and dckr_dpl_emby_gh
  tags:
    - emby
    -  #test
#
- name: Job 24 | import task invidious
  ansible.builtin.import_tasks:
    file: 7601-invidious.yml
  # when: apt_host_pckg_lst | contains bind9
#
- name: Job 25 | import task rxresume
  ansible.builtin.import_tasks:
    file: 8662-rxresume.yml
  # when: apt_host_pckg_lst | contains bind9
#
- name: Job 26 | import task resume
  ansible.builtin.import_tasks:
    file: 5050-resume.yml
  # when: apt_host_pckg_lst | contains bind9
#
- name: Job 27 | import task resume
  ansible.builtin.import_tasks:
    file: 3555-wud.yml
  # when: apt_host_pckg_lst | contains bind9
#
- name: Job 28 | import task webpdf
  ansible.builtin.import_tasks:
    file: 25568-webpdf.yml
  # when: apt_host_pckg_lst | contains bind9
#
- name: Job 29 | import task stirling-pdf
  ansible.builtin.import_tasks:
    file: 25568-stirling-pdf.yml
  # when: apt_host_pckg_lst | contains bind9
#
- name: Job 30 | import task meryem
  ansible.builtin.import_tasks:
    file: 8090-meryem.yml
  when: instl_docker_pckg and dckr_dpl_meryem
  tags:
    - meryem
    -  #test
#
- name: Job 31 | import task anasse
  ansible.builtin.import_tasks:
    file: 8092-anasse.yml
  when: instl_docker_pckg and dckr_dpl_anasse
  tags:
    - anasse
    -  #test
#
- name: Job 32 | import task opendot
  ansible.builtin.import_tasks:
    file: 8098-opendot.yml
  when: instl_docker_pckg and dckr_dpl_opendot
  tags:
    - opendot
    -  #test
#
- name: Job 32 | import task opendot
  ansible.builtin.import_tasks:
    file: 8099-topendot.yml
  when: instl_docker_pckg and dckr_dpl_opendot
  tags:
    - opendot
    -  #test
#
- name: Job 33 | import task Skylinewebservice
  ansible.builtin.import_tasks:
    file: 8094-skylinewebservice.com.yml
  when: instl_docker_pckg and dckr_dpl_skyline
  tags:
    - skyline
    -  #test
#
- name: Job 33-1 | import task tSkylinewebservice
  ansible.builtin.import_tasks:
    file: 8095-tskylinewebservice.com.yml
  when: instl_docker_pckg and dckr_dpl_skyline
  tags:
    - skyline
    -  #test
#
- name: Job 34 | import task Skylinewebservice
  ansible.builtin.import_tasks:
    file: 8100-reddot.africa.yml
  when: instl_docker_pckg and dckr_dpl_reddot_africa
  tags:
    - reddot_africa
    -  #test
#
- name: Job 34 | import task Skylinewebservice
  ansible.builtin.import_tasks:
    file: 8102-blingbody.yml
  when: instl_docker_pckg and dckr_dpl_blingbody
  tags:
    - blingbody
    -  #test
#
- name: Job 35 | import task webcheck
  ansible.builtin.import_tasks:
    file: 6160-webcheck.yml
  when: instl_docker_pckg and dckr_dpl_webcheck
  tags:
    - webcheck
    # - test
#
- name: Job 36 | import task uptimekuma
  ansible.builtin.import_tasks:
    file: 3444-uptime_kuma.yml
  when: instl_docker_pckg and dckr_dpl_uptmkm
  tags:
    - uptimekuma
    # - test
#
- name: Job 37 | import task activ
  ansible.builtin.import_tasks:
    file: 8104-activ.yml
  when: instl_docker_pckg and dckr_dpl_activ
  tags:
    - activ
    -  #test
#
- name: Job 38 | import task spotube
  ansible.builtin.import_tasks:
    file: 8106-spotube.yml
  when: instl_docker_pckg and dckr_dpl_spotube
  tags:
    - spotube
    -  #test
#
- name: Job 39 | import task spotube
  ansible.builtin.import_tasks:
    file: 8108-jmj.yml
  when: instl_docker_pckg and dckr_dpl_jmj
  tags:
    - jmj
    -  #test
#
- name: Job 40 | import task gpt
  ansible.builtin.import_tasks:
    file: 3003-gpt.yml
  when: instl_docker_pckg and dckr_dpl_gpt
  tags:
    - gpt
    -  #test
#
- name: Job 41 | import task rustdesk
  ansible.builtin.import_tasks:
    file: 2118-rustdesk.yml
  when: instl_docker_pckg and dckr_dpl_rustdesk
  tags:
    - rustdesk
    # - test
#
- name: Job 42 | import task n8n
  ansible.builtin.import_tasks:
    file: 5678-n8n.yml
  when: instl_docker_pckg and dckr_dpl_n8n
  tags:
    - n8n
    - test
#
#
#
# keep this last
- name: Job 99 | import task prune
  ansible.builtin.import_tasks:
    file: prune.yml
  when: instl_docker_pckg
  tags:
    - prune
    -  #test
#
# command: touch "{{ item.item }}"
#   with_items:
#       - { item: "1" }
#       - { item: "2" }
#       - { item: "3" }
