---
# tasks file for bashrc
- name: Job 01 | copy .bashrc file to ibrahim
  copy:
    src: "files/home/ibrahim/"
    dest: "/home/ibrahim/"
    owner: ibrahim
    group: ibrahim
    mode: "0744"
  when: ansible_os_family == 'Debian'
  # tags: test
#
- name: Job 02 | copy .ssh/config file to ibrahim
  copy:
    src: "files/home/.ssh/config"
    dest: "/home/ibrahim/.ssh/"
    owner: ibrahim
    group: ibrahim
    mode: "0644"
  when: ansible_os_family == 'Debian'
  # tags: test
#
- name: Job 03 | copy .bashrc file to root
  copy:
    src: "files/home/ibrahim/.bashrc"
    dest: "/root/"
    owner: root
    group: root
    mode: "0744"
  when: ansible_os_family == 'Debian'
  # tags: test
#
- name: Job 04 | copy .ssh/config file to root
  copy:
    src: "files/home/.ssh/config"
    dest: "/root/.ssh/"
    owner: root
    group: root
    mode: "0644"
  when: ansible_os_family == 'Debian'
  # tags: test
#
#  # copy same to localusers
- name: Job 05 | copy .bashrc file to localusers
  copy:
    src: "files/home/ibrahim/.bashrc"
    dest: "/home/{{item.name}}/"
    owner: "{{item.name}}"
    group: "{{item.name}}"
    mode: "0744"
  when: addLocalUser
  loop: "{{ localusers }}"
  tags:
    - localusers
    # - test
#
- name: Job 06 | copy .ssh/config file to localusers
  copy:
    src: "files/home/.ssh/config"
    dest: "/home/{{item.name}}/.ssh/"
    owner: "{{item.name}}"
    group: "{{item.name}}"
    mode: "0644"
  when: addLocalUser
  loop: "{{ localusers }}"
  tags:
    - localusers
    # - test
#
