#  #
# - name: Job 01.3.1 | Update network configuration.
#   interfaces_file:
#     dest: /etc/network/interfaces
#     iface:  "{{interfaces.iface}}"
#     backup: true
#     state: present
#     mode: "0644"
#     owner: root
#     group: root
#
# - name: Job 01.3.1 | Update network configuration.
# lineinfile:
#   dest: /etc/network/interfaces
#   regexp: "{{ item.regexp }}"
#   line: "{{ item.line }}"
#   state: present
#   #validate: 'sshd -t -f %s'
# with_items:
#   - regexp: "^INTERFACESv4"
#     line: "{{dsbl_dhcpvsx}}"
#   # - regexp: "^PermitRootLogin"
#   #   line: "PermitRootLogin no"
#   # - regexp: "^Port"
#   #   line: "Port 22"
#   # - regexp: "^PubkeyAuthentication"
#   #   line: "PubkeyAuthentication yes"
#   # - regexp: "^ChallengeResponseAuthentication"
#   #   line: "ChallengeResponseAuthentication no"
#   # - regexp: "^PermitEmptyPasswords"
#   #   line: "PermitEmptyPasswords no"
#   # - regexp: "^AllowAgentForwarding"
#   #   line: "AllowAgentForwarding yes"
# notify: Restart dhcp
# when: dsbl_dhcpvsx
#  #tags: test
#
- name: Job 01.7.3 | Copy network folder to target host that matches "inventory_hostname"
  copy:
    src: "files/{{inventory_hostname}}/etc/network"
    dest: "/etc/"
    owner: root
    group: root
    mode: "0644"
  # when: inventory_hostname != 'virthost01'
  notify:
    - Restart networking
    - Restart docker
  # tags: test
  #
  #
# - name: Deploy network interfaces configuration
#   template:
#     src: interfaces.j2
#     dest: /etc/network/interfaces
#     owner: root
#     group: root
#     mode: '0644'
#   notify: Restart networking
#   when: network_interfaces is defined and network_interfaces | length > 0
#   tags:
#     - network
#     #- test
#
- name: Deploy network interfaces configuration
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces # come into me, my precioussssss
    owner: root
    group: root
    mode: "0644"
  register: interfaces_template
  when: network_interfaces_check

- name: Restart networking (safe)
  service:
    name: networking
    state: restarted
  when:
    - interfaces_template.changed
    - ssh_interface != default_interface
    - network_interfaces_check
