---
# https://code.visualstudio.com/docs/setup/linux#_install-vs-code-on-linux
- name: Pre-accept Microsoft repository EULA
  debconf:
    name: code
    question: code/add-microsoft-repo
    value: "true"
    vtype: boolean

- name: Install required system packages
  apt:
    name:
      - wget
      - gpg
      - apt-transport-https
    state: present
    update_cache: true

- name: Download Microsoft GPG key
  get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /tmp/microsoft.asc
    mode: '0644'

- name: Install Microsoft GPG key into keyring
  command:
    cmd: gpg --dearmor -o {{ vscode_keyring_path }} /tmp/microsoft.asc
    creates: "{{ vscode_keyring_path }}"

- name: Set permissions on Microsoft keyring
  file:
    path: "{{ vscode_keyring_path }}"
    owner: root
    group: root
    mode: '0644'

- name: Add Visual Studio Code APT repository
  apt_repository:
    repo: >
      deb [arch={{ vscode_architectures }} signed-by={{ vscode_keyring_path }}]
      {{ vscode_repo_url }} stable main
    filename: vscode
    state: present

- name: Update APT cache
  apt:
    update_cache: true

- name: Install Visual Studio Code
  apt:
    name: "{{ vscode_package }}"
    state: present