---
# handlers file for configs
#
- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
#
- name: Restart networking
  ansible.builtin.service:
    name: networking
    state: restarted
#
- name: Restart dhcp
  ansible.builtin.service:
    name: isc-dhcp-server
    state: restarted
#
- name: Restart bind9
  ansible.builtin.service:
    name: bind9
    state: restarted
#
- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
#
- name: Restart sensu-services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - sensu-api
    - sensu-client
    - sensu-server
#
# gnomerdp
- name: Restart gnome remote desktop (user)
  ansible.builtin.shell: |
    systemctl --user restart gnome-remote-desktop.service
  become: true
  become_user: "{{ gnome_rdp_user }}"

- name: Restart gnome remote desktop (system)
  ansible.builtin.systemd:
    name: gnome-remote-desktop
    state: restarted
    enabled: true
#
- name: restart gnome remote desktop
  ansible.builtin.systemd:
    name: gnome-remote-desktop
    state: restarted
    daemon_reload: true
#
- name: Restart Docker
  service:
    name: docker
    state: restarted
#
- name: Restart xrdp
  systemd:
    name: xrdp
    state: restarted

- name: Restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
#
#
#
# https://serverfault.com/questions/796067/is-it-possible-to-notify-a-group-of-services-instead-of-individual-in-ansible
# notify:
#   - "restart sensu-services"


# handlers:
# - name: restart sensu api
#   listen: "restart sensu-services"
#   service: name=sensu-api state=restarted
#   ignore_errors: true

# - name: restart sensu service
#   listen: "restart sensu-services"
#   service: name=sensu-service state=restarted
#   ignore_errors: true

# - name: restart sensu client
#   listen: "restart sensu-services"
#   service: name=sensu-client state=restarted
#   ignore_errors: true
