hostname_additional_hosts:
  - ip_address: 10.1.0.201
    hostname: de-debian13.skyline.lan
    hostname_short: de-debian13
  - ip_address: 192.168.77.201
    hostname: de-debian13.skyline.lan
    hostname_short: de-debian13
  - ip_address: 192.168.0.201
    hostname: de-debian13.skyline.lan
    hostname_short: de-debian13
  #
dckr_dmain_nme_pstfx: home.sawadogo.xyz
#virthost01.skyline.lan:
#ansible_connection: local # this will overwrite any other type of connections. its needed here.
ansible_become_pass: "{{ localhost_become_pass }}"
#
### PRVS | CONFIG ###
prvs_copy_home: false # Copy default user's home files in place
prvs_root_passwd: false # update root passward
#
dkr_copy_def_files: false # Copy default docker files to target server
#
crntb_activate_cronjobs: false
#
addLocalUser: true # add a local user to specific host
#
addresolv: true # add nameservers to resolv.conf
#
### APT | PACKAGES INSTALL ###
instl_def_pckg: true # Install complete packages. A 'no' will remove it from the host (apt_def_pckg_lst)
instl_utl_pckg: true # Install complete packages. A 'no' will remove it from the host (apt_util_lst)
sysd_strt_srvc: true # Start services
instl_ansbl_pckg: true # Install ansible using PIP (pip_ansbl_pckg_lst apt_ansbl_pckg_lst)
instl_docker_pckg: true # Install Docker package (apt_docker_pckg_lst)
apt_host_pckg_lst: # Install Host Specific Packages (keep this empty. use host_var to overwrite it)
  - cifs-utils
  - isc-dhcp-common
  - isc-dhcp-server
  - kubectx
  - python3-docker
  - docker-cli
#
#
pip_host_pckg_lst: # Install Host Specific PIP Packages when ansible is also installed
  - docker
#
docker3: true # Install Docker
#
# docker containers
dckr_dpl_pihole: true
dckr_dpl_ispy: false
dckr_dpl_semaphore: true
dckr_dpl_trcmmnd: false
dckr_dpl_npxymgmt: true
dckr_dpl_gravity: true
dckr_dpl_homepage: true
dckr_dpl_wud: true
dckr_dpl_webcheck: true
dckr_dpl_uptmkm: true
dckr_dpl_n8n: true # add n8n to this list and set it to true to have it deployed on the target host
#
apt_hst_strt_srvc_lst: # Ensure Host Specific Services are running.
  - isc-dhcp-server
#
odoo_keep_alive: true # Install Odoo keep alive cronjob
#
#
#
instl_dhcp_srvc: true
dsbl_dhcpvsx: true # Disable dhcp v6 in DHCP
dsbl_dhcpvsx_regx: INTERFACESv4='eno1' # text that should change goes here eg. INTERFACESv4='ens18'
#
copy_iptables: true # Copy iptables to /root folder
strt_myiptbls_at_boot: true
#
gnomerdp: true # Install and configure GNOME Remote Desktop (RDP)
#
# interfaces:
#   - iface: eth1
#
localusers:
  - name: mobile
    shell: /bin/bash
    groups:
      - mobile
    append: false
    state: present
    key: mobile.pub
    create_home: true
    local: true
    hosts: de-debian13
  - name: lady
    shell: /bin/bash
    # group: lady
    groups:
      - sudo
      - docker
    append: true
    state: present
    key: lady.pub
    gen_ssh_key: true
    create_home: true
    local: true
