hostname_additional_hosts:
  - ip_address: 217.154.243.72
    hostname: de-debian13-vps.imsawadogo.com
    hostname_short: de-debian13-vps
  # - ip_address: 192.168.77.201
  #   hostname: de-debian13-vps.skyline.lan
  #   hostname_short: de-debian13-vps
  # - ip_address: 192.168.0.201
  #   hostname: de-debian13-vps.skyline.lan
  #   hostname_short: de-debian13-vps
  #
dckr_dmain_nme_pstfx: home.sawadogo.xyz
# virthost01.skyline.lan:
# ansible_connection: local  # this will overwrite any other type of connections. its needed here.
ansible_become_pass: "{{ localhost_become_pass }}"
#
#  ## PRVS | CONFIG  ###
prvs_copy_home: false # Copy default user's home files in place
prvs_root_passwd: false # update root passward
#
dkr_copy_def_files: false # Copy default docker files to target server
#
crntb_activate_cronjobs: false
#
addLocalUser: false # add a local user to specific host
#
addresolv: true # add nameservers to resolv.conf
#
#  ## APT | PACKAGES INSTALL  ###
instl_def_pckg: true # Install complete packages. A 'no' will remove it from the host (apt_def_pckg_lst)
instl_utl_pckg: true # Install complete packages. A 'no' will remove it from the host (apt_util_lst)
sysd_strt_srvc: true # Start services
instl_ansbl_pckg: true # Install ansible using PIP (pip_ansbl_pckg_lst apt_ansbl_pckg_lst)
instl_docker_pckg: true # Install Docker package (apt_docker_pckg_lst)
apt_host_pckg_lst: # Install Host Specific Packages (keep this empty. use host_var to overwrite it)
  - cifs-utils
  # - isc-dhcp-common
  # - isc-dhcp-server
  # - kubectx
  # - python3-docker
  # - docker-cli
#
#
pip_host_pckg_lst: # Install Host Specific PIP Packages when ansible is also installed
  # - docker
#
docker3: true # Install Docker
#
# docker containers
dckr_dpl_pihole: false
dckr_dpl_ispy: false
dckr_dpl_semaphore: false
dckr_dpl_trcmmnd: false
dckr_dpl_npxymgmt: false
dckr_dpl_gravity: false
dckr_dpl_homepage: false
dckr_dpl_wud: false
dckr_dpl_webcheck: false
dckr_dpl_uptmkm: false
dckr_dpl_n8n: false # add n8n to this list and set it to true to have it deployed on the target host
#
apt_hst_strt_srvc_lst: # Ensure Host Specific Services are running.
  # - isc-dhcp-server
#
odoo_keep_alive: false # Install Odoo keep alive cronjob
#
#
#
instl_dhcp_srvc: false
dsbl_dhcpvsx: false # Disable dhcp v6 in DHCP
# dsbl_dhcpvsx_regx: INTERFACESv4='eno1'          # text that should change goes here eg. INTERFACESv4='ens18'
#
copy_iptables: false # Copy iptables to /root folder
strt_myiptbls_at_boot: false
#
gnomerdp: true # Install and configure GNOME Remote Desktop (RDP)
#
xrdp: true # Install and configure xrdp
#
# interfaces:
#   - iface: eth1
#
# localusers:
#   - name: ibrahim
#     password: "{{ 'ibrahim' | password_hash('sha512') }}"
#     shell: /bin/bash
#     groups: sudo
#  #

media_apps:
  overseerr:
    enabled: true
  seerr:
    enabled: false
