hostname_additional_hosts:
  - ip_address: 192.168.14.254
    hostname: virthost01.skyline.lan
    hostname_short: virthost01
  - ip_address: 192.168.77.254
    hostname: virthost01.skyline.lan
    hostname_short: virthost01
  - ip_address: 192.168.8.254
    hostname: virthost01.skyline.lan
    hostname_short: virthost01
  #
apt_host_packages_list: # Install Host Specific Packages
  - rsync
  - pip
#
apt_remove_package_lists: # Remove APT package lists
#
pip_install_package_lists: # Install packages using PIP
  - ansible
  - passlib
#
ansible_become_pass: "{{ localhost_become_pass }}"
#
prvs_copy_home: no # Copy default user's home files in place
#
dkr_copy_def_files: no # Copy default docker files to target server
#
apt_install_utilities_base: yes # Install utilities packages default settings

# 127.0.0.1       localhost
# 127.0.1.1       virthost01.skyline.lan  virthost01

# # The following lines are desirable for IPv6 capable hosts
# ::1     localhost ip6-localhost ip6-loopback
# ff02::1 ip6-allnodes
# ff02::2 ip6-allrouters
#
#virthost01.skyline.lan:
ansible_connection: local # this will overwrite any other type of connections. its needed here.
