---

- hosts: local
  connection: local
  # ansible_check_mode: false  # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_checkmode.html

  vars_files:
    - ansible-vault.yml

  roles:
    - provisions
    - ssh
    - ansible
    - apt-packages
    - bashrc
    - dockers
    - update
  #
# complete and not tested.
