---
- name: HOSTNAME | Initialisation
  hosts: allservers
  gather_facts: true
  ignore_errors: true
  ignore_unreachable: true
  # remote_user: root
  remote_user: ibrahim
  become: true
  become_user: root
  roles:
    - hostname
# - name: HOSTNAME | Initialisation - LOCALHOST
#   hosts: local
#   ignore_errors: true
#   ignore_unreachable: true
#   connection: local
#   # remote_user: root
#   remote_user: ibrahim
#   become: true
#   become_user: root
#   roles:
#     - hostname

# complete, tested and working
