---
- name: PROVISIONS | First time Initialisation
  hosts: firstimeonly
  gather_facts: true
  ignore_errors: true
  ignore_unreachable: true
  remote_user: root
  # remote_user: ibrahim
  become: true
  become_user: root
  become_method: su

  pre_tasks:
    - name: PRE TASK | Check if ansible is installed
      ansible.builtin.command:
        cmd: ansible --version
      register: ansible_check
      ignore_errors: true
      changed_when: false

    - name: PRE TASK | Install required packages
      ansible.builtin.package:
        name:
          - python3
          - sudo
        state: present
      when: ansible_check.rc != 0

    - name: PRE TASK | Install adm packages before starting roles
      ansible.builtin.apt:
        name:
          - python3
          - sudo
        state: present

  roles:
    - ssh
    - provisions
    - reboot

# - name: PROVISIONS | First time Initialisation - LOCALHOST
#   hosts: local
#   ignore_errors: true
#   ignore_unreachable: true
#   connection: local
#   # remote_user: root
#   remote_user: ibrahim
#   become: true
#   become_user: root
#   roles:
#     - provisions
#     - ssh

# - name: PROVISIONS | First time Initialisation - VMS
#   hosts: vms
#   #connection: local
#   remote_user: vagrant
#   #remote_user: ibrahim
#   become: true
#   become_user: root
#   roles:
#     - provisions
#     - ssh

# complete, tested and working
