---
- name: ICINGA | Install icinga1 manually
  hosts: localhost
  gather_facts: true
  connection: local
  ignore_errors: false
  ignore_unreachable: false
  # remote_user: root
  # remote_user: ibrahim
  become: true
  become_user: root

  vars_files:
    - ../ansible-vault.yml

  roles:
    - icinga
