---
- name: DOCEKERS | Initialisation
  hosts: allservers
  gather_facts: true
  ignore_errors: true
  ignore_unreachable: false
  # remote_user: root
  remote_user: ibrahim
  become: true
  become_user: root

  vars_files:
    - ../ansible-vault.yml

  roles:
    - dockers
# - name: DOCEKERS | Initialisation - LOCALHOST
#   hosts: local
#   ignore_errors: true
#   ignore_unreachable: true
#   connection: local
#   # remote_user: root
#   remote_user: ibrahim
#   become: true
#   become_user: root
#   roles:
#     - dockers

# complete, tested and working
