---
- name: PROVISIONS | First time Initialisation
  hosts: windows_users
  # gather_facts: true

  #
  gather_facts: true

  vars_files:
    - ../ansible-vault.yml

  vars:
    ansible_shell_type: cmd
    logpath: C:\ansible-log
    filename: "{{ lookup('pipe', 'date +%Y%m%d') }}.log"

  roles:
    - win_update
# ansible_user: username@MY.DOMAIN.COM
# ansible_password: Password

#  # psrp
# ansible_connection: psrp
# ansible_psrp_auth: negotiate  # or kerberos to disable ntlm fallback

#  # winrm
# ansible_connection: winrm
# ansible_winrm_transport: kerberos

# RESOURCES
# https://docs.ansible.com/ansible/latest/os_guide/windows_winrm.html#windows-winrm
# https://www.bing.com/search?FORM=U523DF&PC=U779&q=ansible+connection+to+windows+11&ntref=1
# https://woshub.com/ansible-manage-windows-machines/
#
