---
- name: BASHRC | Initialisation
  hosts: allservers
  gather_facts: true
  ignore_errors: true
  ignore_unreachable: true
  remote_user: ibrahim
  #become: false
  become: true
  roles:
    - bashrc
# - name: BASHRC | Initialisation - LOCALHOST
#   hosts: local
#   ignore_errors: true
#   ignore_unreachable: true
#   connection: local
#   remote_user: ibrahim
#   become: false
#   roles:
#     - bashrc
