---
# tasks file for configs
- name: Job 1001-1001 | import task timezone
  ansible.builtin.import_tasks:
    file: timezone.yml
  tags:
    - timezone
    - localhost
    #- test
#
- name: Job 1001-1002 | import task locales
  ansible.builtin.import_tasks:
    file: locales.yml
  when: ansible_os_family == "Debian"
  tags:
    - locales
    - localhost
    #- test#
#
- name: Job 1001-1002 | import task locales
  ansible.builtin.import_tasks:
    file: sleepy.yml
  when: ansible_os_family == "Debian"
  tags:
    - locales
    - localhost
    #- test
#
- name: Job 1001-1003 | import task user_mgmt
  ansible.builtin.import_tasks:
    file: user_mgmt.yml
  when: ansible_os_family == "Debian"
  tags:
    - user_mgmt
    - localhost
    #- test
#
- name: Job 98 | import task github key
  ansible.builtin.import_tasks:
    file: github_key.yml
  when: instl_docker_pckg and instl_gthb_ky
  tags:
    - github_key
    #- test  
#