- name: Disable system sleep, suspend, hibernate, and hybrid-sleep
  ansible.builtin.systemd:
    name: "{{ item }}"
    masked: true
    enabled: false
  loop:
    - sleep.target
    - suspend.target
    - hibernate.target
    - hybrid-sleep.target

# defensive measure to prevent accidental sleep, suspend, hibernate, and hybrid-sleep
- name: Stop and mask all sleep-related systemd targets
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    masked: true
    enabled: false
  loop:
    - sleep.target
    - suspend.target
    - hibernate.target
    - hybrid-sleep.target
